//
// EmbedAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class EmbedAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func embedCreate(completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        embedCreateWithRequestBuilder().execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /embed
     - 

     - BASIC:
       - type: http
       - name: Basic

     - returns: RequestBuilder<Void> 
     */
    open class func embedCreateWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/embed"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func embedList(completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        embedListWithRequestBuilder().execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - GET /embed
     - 

     - BASIC:
       - type: http
       - name: Basic

     - returns: RequestBuilder<Void> 
     */
    open class func embedListWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/embed"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
